name: econauta
description: >-
  Econauta es un simulador educativo de politica economica para estudiantes
  universitarios de Economia, Administracion Publica y Finanzas.
publish_to: "none"
version: 1.0.2+3

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.8.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.0 <6.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
